apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-financia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-financia
  template:
    metadata:
      labels:
        app: frontend-financia
    spec:
      containers:
      - name: frontend-financia
        image: financiacompleto-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5173